package com.zxl.blog.db.mapper.base;

import com.zxl.blog.db.entities.ArtcleContent;
import com.zxl.blog.db.entities.ArtcleContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArtcleContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artcle_content
     *
     * @mbggenerated
     */
    int countByExample(ArtcleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artcle_content
     *
     * @mbggenerated
     */
    int deleteByExample(ArtcleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artcle_content
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artcle_content
     *
     * @mbggenerated
     */
    int insert(ArtcleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artcle_content
     *
     * @mbggenerated
     */
    int insertSelective(ArtcleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artcle_content
     *
     * @mbggenerated
     */
    List<ArtcleContent> selectByExampleWithBLOBs(ArtcleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artcle_content
     *
     * @mbggenerated
     */
    List<ArtcleContent> selectByExample(ArtcleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artcle_content
     *
     * @mbggenerated
     */
    ArtcleContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artcle_content
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ArtcleContent record, @Param("example") ArtcleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artcle_content
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ArtcleContent record, @Param("example") ArtcleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artcle_content
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ArtcleContent record, @Param("example") ArtcleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artcle_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArtcleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artcle_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ArtcleContent record);
}