package com.zxl.blog.db.mapper.base;

import com.zxl.blog.db.entities.ArticleType;
import com.zxl.blog.db.entities.ArticleTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated
     */
    int countByExample(ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated
     */
    int deleteByExample(ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated
     */
    int insert(ArticleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated
     */
    int insertSelective(ArticleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated
     */
    List<ArticleType> selectByExample(ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated
     */
    ArticleType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ArticleType record, @Param("example") ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ArticleType record, @Param("example") ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArticleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArticleType record);
}