package com.zxl.blog.db.entities;

import java.io.Serializable;

public class ArtcleContent implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column artcle_content.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column artcle_content.art_content
     *
     * @mbggenerated
     */
    private String artContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table artcle_content
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column artcle_content.id
     *
     * @return the value of artcle_content.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column artcle_content.id
     *
     * @param id the value for artcle_content.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column artcle_content.art_content
     *
     * @return the value of artcle_content.art_content
     *
     * @mbggenerated
     */
    public String getArtContent() {
        return artContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column artcle_content.art_content
     *
     * @param artContent the value for artcle_content.art_content
     *
     * @mbggenerated
     */
    public void setArtContent(String artContent) {
        this.artContent = artContent == null ? null : artContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artcle_content
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", artContent=").append(artContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}